language: python
python:
    - "2.7"
before-install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install -qq python-pygame
script:
    - "python setup.py test"
notifications:
    email:
        on_failure: change